### ISSUE TITLE
持久储存定时任务出现ValueError

### ISSUE THREAD

**Issue by nonepage** [nonebot/nonebot#162]
具体报错信息:ValueError: This scheduler already has a job store by the alias of "jobstor_call"
python版本:3.8
大概代码:
```
@on_command('clock', aliases=('闹钟', '定个闹钟'), only_to_me=False)
async def main_clock(session: CommandSession):
    time = session.get('time', prompt=r'请问您要定一个几点的闹钟?')
    # 初始化scheduler
    call_me = SQLAlchemyJobStore(url='sqlite:///' + database_call)
    scheduler.add_jobstore(call_me, alias='jobstor_call')


    # 制作一个“5分钟后”触发器
    delta = datetime.timedelta(minutes=float(time))
    trigger = DateTrigger(
        run_date=datetime.datetime.now() + delta
    )

    # 添加任务
    scheduler.add_job(
        func=session.send,  # 要添加任务的函数，不要带参数
        trigger=trigger,  # 触发器
        args=('您定的闹钟时间到了',),  # 函数的参数列表，注意：只有一个值时，不能省略末尾的逗号
        misfire_grace_time=60,
        jobstore='jobstore_call',
    )

    await session.send('已经为您订好了一个' + time + '分钟的闹钟')

```
如果把add_jobstore拿出去,像这样:

```
# 初始化scheduler
call_me = SQLAlchemyJobStore(url='sqlite:///' + database_call)
scheduler.add_jobstore(call_me, alias='gdfsgdfs')


@on_command('clock', aliases=('闹钟', '定个闹钟'), only_to_me=False)
async def main_clock(session: CommandSession):
    time = session.get('time', prompt=r'请问您要定一个几点的闹钟?')



    # 制作一个“5分钟后”触发器
    delta = datetime.timedelta(minutes=float(time))
    trigger = DateTrigger(
        run_date=datetime.datetime.now() + delta
    )

    # 添加任务
    scheduler.add_job(
        func=session.send,  # 要添加任务的函数，不要带参数
        trigger=trigger,  # 触发器
        args=('您定的闹钟时间到了',),  # 函数的参数列表，注意：只有一个值时，不能省略末尾的逗号
        misfire_grace_time=60,
        id='1',
        jobstore='store_tell',
    )

    await session.send('已经为您订好了一个' + time + '分钟的闹钟')
```
又会弹出这个报错
```
 File "C:\Users\chend\AppData\Local\Programs\Python\Python38-32\lib\site-packages\apscheduler\schedulers\base.py", line 790, in _lookup_jobstore
    raise KeyError('No such job store: %s' % alias)
KeyError: 'No such job store: store_tell'
```
问:有办法解决持久储存的问题吗?

**Comment by nonepage** [comment]
求求大佬看我一眼,秋梨膏

**Comment by yanyongyu** [comment]
> 具体报错信息:ValueError: This scheduler already has a job store by the alias of "jobstor_call"
> python版本:3.8
> 大概代码:
> 
> ```
> @on_command('clock', aliases=('闹钟', '定个闹钟'), only_to_me=False)
> async def main_clock(session: CommandSession):
>     time = session.get('time', prompt=r'请问您要定一个几点的闹钟?')
>     # 初始化scheduler
>     call_me = SQLAlchemyJobStore(url='sqlite:///' + database_call)
>     scheduler.add_jobstore(call_me, alias='jobstor_call')
> 
> 
>     # 制作一个“5分钟后”触发器
>     delta = datetime.timedelta(minutes=float(time))
>     trigger = DateTrigger(
>         run_date=datetime.datetime.now() + delta
>     )
> 
>     # 添加任务
>     scheduler.add_job(
>         func=session.send,  # 要添加任务的函数，不要带参数
>         trigger=trigger,  # 触发器
>         args=('您定的闹钟时间到了',),  # 函数的参数列表，注意：只有一个值时，不能省略末尾的逗号
>         misfire_grace_time=60,
>         jobstore='jobstore_call',
>     )
> 
>     await session.send('已经为您订好了一个' + time + '分钟的闹钟')
> ```
> 
> 如果把add_jobstore拿出去,像这样:
> 
> ```
> # 初始化scheduler
> call_me = SQLAlchemyJobStore(url='sqlite:///' + database_call)
> scheduler.add_jobstore(call_me, alias='gdfsgdfs')
> 
> 
> @on_command('clock', aliases=('闹钟', '定个闹钟'), only_to_me=False)
> async def main_clock(session: CommandSession):
>     time = session.get('time', prompt=r'请问您要定一个几点的闹钟?')
> 
> 
> 
>     # 制作一个“5分钟后”触发器
>     delta = datetime.timedelta(minutes=float(time))
>     trigger = DateTrigger(
>         run_date=datetime.datetime.now() + delta
>     )
> 
>     # 添加任务
>     scheduler.add_job(
>         func=session.send,  # 要添加任务的函数，不要带参数
>         trigger=trigger,  # 触发器
>         args=('您定的闹钟时间到了',),  # 函数的参数列表，注意：只有一个值时，不能省略末尾的逗号
>         misfire_grace_time=60,
>         id='1',
>         jobstore='store_tell',
>     )
> 
>     await session.send('已经为您订好了一个' + time + '分钟的闹钟')
> ```
> 
> 又会弹出这个报错
> 
> ```
>  File "C:\Users\chend\AppData\Local\Programs\Python\Python38-32\lib\site-packages\apscheduler\schedulers\base.py", line 790, in _lookup_jobstore
>     raise KeyError('No such job store: %s' % alias)
> KeyError: 'No such job store: store_tell'
> ```
> 
> 问:有办法解决持久储存的问题吗?

文档里有写哦，apscheduler的配置方法

<https://nonebot.cqp.moe/api.html#apscheduler-config>

示例：
```python
APSCHEDULER_CONFIG = {
    'apscheduler.timezone': 'Asia/Shanghai',
    'apscheduler.jobstores.default': {
        'type': 'sqlalchemy',
        'url': f'mysql+pymysql://{mysql_user}:{mysql_password}'
               f'@{mysql_host}:{mysql_port}/{mysql_database}?charset=utf8mb4',
        'tablename': 'apscheduler_jobs'
    }
}
```

**Comment by richardchien** [comment]
scheduler.add_jobstore 你可以在插件 py 文件的全局范围的开头运行，或者用 [这个装饰器](https://nonebot.cqp.moe/api.html#decorator-on-startup)

**Comment by nonepage** [comment]
谢谢两位大佬嗷,我去试试看先

**Comment by nonepage** [comment]
报错信息:_pickle.PicklingError: Can't pickle <function main_clock at 0x04F56A48>: it's not the same object as App.plugins.Call_me_now.main_clock
代码:
```
@on_startup
async def scheduler_clock():
    call_me = SQLAlchemyJobStore(url=database_call)
    scheduler.add_jobstore(call_me, "call")

@on_command('clock', aliases=('闹钟', '定个闹钟'), only_to_me=False)
async def main_clock(session: CommandSession):
    time = session.get('time', prompt=r'请问您要定一个几点的闹钟?')

    # 制作一个“5分钟后”触发器
    delta = datetime.timedelta(minutes=float(time))
    trigger = DateTrigger(
        run_date=datetime.datetime.now() + delta
    )

    # 添加任务
    scheduler.add_job(
        func=session.send,  # 要添加任务的函数，不要带参数
        trigger=trigger,  # 触发器
        args=('您定的闹钟时间到了',),  # 函数的参数列表，注意：只有一个值时，不能省略末尾的逗号
        misfire_grace_time=60,
        id='1',
        jobstore="call",
    )

    await session.send('已经为您订好了一个' + time + '分钟的闹钟')

```

我人傻了

**Comment by nonepage** [comment]
可以跑起来,就是到这个模块添加任务哪里,就凉了,淦!

**Comment by nonepage** [comment]
这是使用上面老哥的代码,也是一样的报错,😭😭
```
database_call = 'sqlite:///' + os.path.abspath('D:\datebase\date.db')
APSCHEDULER_CONFIG: Dict[str, Any] = {
    'apscheduler.timezone': 'Asia/Shanghai',
    'apscheduler.jobstores.default': {
        'type': 'sqlalchemy',
        'url': database_call,
        'tablename': 'apscheduler_jobs'
    }
}
```
@yanyongyu @richardchien

**Comment by lengthmin** [comment]
这里应该是不能直接使用 `session.send`，我个人感觉是因为 session 内部的一些东西会变？所以 pickle 算不出这个函数实际在哪儿。

解决办法：新建一个函数，传入的参数不要和 session 有关，直接使用 `await bot.send` 等方法。

cc @yanyongyu @richardchien

**Comment by cleoold** [comment]
如果上面提到的解決辦法解決了問題，那麽就關閉了。
