### ISSUE TITLE
CommandGroup

### ISSUE THREAD

**Issue by basket-ball** [nonebot/nonebot#164]
CommandGroup.command中，aliases别名设置没有用，是我设置有误吗
![image](https://user-images.githubusercontent.com/53385583/78463698-9d46c900-7712-11ea-860e-124c345ca136.png)
![image](https://user-images.githubusercontent.com/53385583/78463710-ca937700-7712-11ea-92d9-eee0175fd25f.png)

**Comment by richardchien** [comment]
@basket-ball alias 之后是不需要 command group 的前缀的

**Comment by jks15satoshi** [comment]
@basket-ball 或许第 14 行应该是这样的：
```
@MC.command('status', aliases=('MC',))
```
这样就可以使用 `!MC.status` 指令了。但如何为这个指令再设置别名我就不清楚了。

**Comment by yanyongyu** [comment]
aliases是不考虑command group前缀的

如果你需要实现别名，可以再注册一个command

例：

```python
async def handler(session: CommandSession):
    pass

command1 = MC.command('status')(handler)
command2 = MC.command("xxxx")(handler)
```

**Comment by cleoold** [comment]
在未來實現裏區分一下
* command group 前綴的別名
* sub command 後綴的別名
* 整個 sub command 的別名（這個 issue）
使其全部可以定制怎麽樣？

**Comment by basket-ball** [comment]
> 在未來實現裏區分一下
> 
> * command group 前綴的別名
> * sub command 後綴的別名
> * 整個 sub command 的別名（這個 issue）
>   使其全部可以定制怎麽樣？

能问一个问题么，您现在用什么机器人框架运行nonebot？

**Comment by cleoold** [comment]
> 
> 
> > 在未來實現裏區分一下
> > 
> > * command group 前綴的別名
> > * sub command 後綴的別名
> > * 整個 sub command 的別名（這個 issue）
> >   使其全部可以定制怎麽樣？
> 
> 能问一个问题么，您现在用什么机器人框架运行nonebot？

gocqhttp
