### ISSUE TITLE
关于权限管理功能

### ISSUE THREAD

**Issue by azhaizhai** [nonebot/nonebot#167]
被一个小孩刷屏搞的有点烦。本来是想加个黑名单的。然后去看文档的时候发现貌似没有类似功能，而且文档里的perm管理全是基于聊天类型的，而SUPERUSERS权限又太大了，感觉不够灵活。
我自己写了一个基于redis和mysql的权限管理。首先环境比较麻烦，而且我不是搞py的，代码写的比较丑，就不发上来丢人了。
所以我在想，能不能自带一个可配置的基于函数的权限管理。类似于这种。
```json
{
  "perm": [{
    "function": "weather",
    "anonymous_allow": true,
    "deny": ["123456789"],
    "allow": ["123456789"]
  }],
  "blacklist": ["123456789"]
}
```
当然，我主要是觉得权限管理不太好用，我这个想法主要是参考公司用的权限管理系统。仅做参考。

**Comment by richardchien** [comment]
感谢你的建议，权限管理这块以后应该会更新

**Comment by azhaizhai** [comment]
ok
