### ISSUE TITLE
关于定时任务中断及最大消息长度的疑问

### ISSUE THREAD

**Issue by Cyame** [nonebot/nonebot#168]
感谢开发，开发过程中有几个疑问（可能没太领会到API的意思）

#### 关于nonebot与bot对象的区别

我看到指南里关于信息发送出现了两种写法：
其中一种是：
> import nonebot
> @nonebot.on_command("comm")
>     async def func(session: CommandSession): session.send(<Message_T>)

另外一种是：

> import nonebot
> @nonebot.on_command("comm")
>     async def func(session: CommandSession): 
>     bot = nonebot.get_bot()
>     bot.send_group_msg(group_id = id, message = <Message_T>)

一开始写的时候混用了，调了许久还是回到了示例的用法，想问一下两种操作的区别；
另外在使用session.send的过程中，我发现其中似乎包含字数限制（过长的串发不出去）
请问这个也是和自然语言处理器一样受限于`short message`的长度吗？

#### 关于定时任务中断

因为定时任务不易测试（主要因为我调用的爬虫API有获取上限）所以想做手动命令，
已经把定时的`replace`打开，但是手动执行时扔会报协程冲突，想问该如何处理？

另外，获取结果会与单独运行脚本不一样（是协程的问题吗？）或者有什么潜在的原因吗？

感谢。

**Comment by yanyongyu** [comment]
## 关于两种方式的区别

session.send理解为发送消息给创建该session的用户，相较bot.send_*直接调用API来说有明确的指向

也就是说通过bot调用API更加灵活可以做更多的事情（比如转发）

*题外话：bot可以不用 `get_bot()` 直接使用 `session.bot` 即可*

**Comment by yanyongyu** [comment]
#### 定时任务

定时任务能否具体描述一下

协程中爬虫应使用异步库，如 [httpx](https://www.python-httpx.org/) [aiohttp](https://docs.aiohttp.org/en/stable/) ，而非requests这种

**Comment by water-lift** [comment]
@yanyongyu https://github.com/nonebot/nonebot/issues/145

**Comment by water-lift** [comment]
文档咕了（

**Comment by Cyame** [comment]
> #### 定时任务
> 定时任务能否具体描述一下
> 
> 协程中爬虫应使用异步库，如 [httpx](https://www.python-httpx.org/) [aiohttp](https://docs.aiohttp.org/en/stable/) ，而非requests这种

现在其实基本解决了这个问题 但不是通过修改定时（感觉像是异步的问题）

这个定时任务一开始内部实现是从爬虫获取推特数据，然后send到QQ里
（当时是get有log，但是没有send成功）

后来把这个模块拆分了，做了两个定时，一个定时是获取，另一个定时是nonebot端的发送。先获取到txt暂存，然后发送重新读文件，这样功能就正常了。
所以想问的其实是async编程 可以设置线程等待吗）

**Comment by Cyame** [comment]
> ### 关于两种方式的区别
> session.send理解为发送消息给创建该session的用户，相较bot.send_*直接调用API来说有明确的指向
> 
> 也就是说通过bot调用API更加灵活可以做更多的事情（比如转发）
> 
> _题外话：bot可以不用 `get_bot()` 直接使用 `session.bot` 即可_
> 
> 消息长度nonebot并没有限制，QQ是有限制的

了解了，感谢！

**Comment by Cyame** [comment]
> > #### 定时任务
> > 定时任务能否具体描述一下
> > 协程中爬虫应使用异步库，如 [httpx](https://www.python-httpx.org/) [aiohttp](https://docs.aiohttp.org/en/stable/) ，而非requests这种
> 
> 现在其实基本解决了这个问题 但不是通过修改定时（感觉像是异步的问题）
> 
> 这个定时任务一开始内部实现是从爬虫获取推特数据，然后send到QQ里
> （当时是get有log，但是没有send成功）
> 
> 后来把这个模块拆分了，做了两个定时，一个定时是获取，另一个定时是nonebot端的发送。先获取到txt暂存，然后发送重新读文件，这样功能就正常了。
> 所以想问的其实是async编程 可以设置线程等待吗）

我感觉我这个爬虫，应该是个Get命令，延时也比较大（即便上了服务器也不快）
所以原因其实是在这里吗
