### ISSUE TITLE
docker安装出现错误了，请问怎么解决

### ISSUE THREAD

**Issue by jw-star** [nonebot/nonebot#170]
cqhttp_1   | [fix-attrs.d] 010-app: exited 0.
cqhttp_1   | [fix-attrs.d] done.
cqhttp_1   | [cont-init.d] executing container initialization scripts...
cqhttp_1   | [cont-init.d] 010-setup-vnc: executing... 
cqhttp_1   | Would you like to enter a view-only password (y/n)? Password:Verify:[cont-init.d] 010-setup-vnc: exited 0.
cqhttp_1   | [cont-init.d] 020-setup-sudo: executing... 
cqhttp_1   | [cont-init.d] 020-setup-sudo: exited 0.
cqhttp_1   | [cont-init.d] 110-get-coolq: executing... 
cqhttp_1   | CoolQ already exists, skip download.
cqhttp_1   | DEBUG: 插件版本已锁定，正在覆盖 cpk 文件……
cqhttp_1   | ERROR: [Errno 13] Permission denied: '/home/user/coolq/app/io.github.richardchien.coolqhttpapi.cpk'
cqhttp_1   | Traceback (most recent call last):
cqhttp_1   |   File "/home/user/bootstrap.py", line 169, in <module>
cqhttp_1   |     bootstrap()
cqhttp_1   |   File "/home/user/bootstrap.py", line 144, in bootstrap
cqhttp_1   |     copy_cpk()
cqhttp_1   |   File "/home/user/bootstrap.py", line 40, in copy_cpk
cqhttp_1   |     shutil.copyfile(CPK_FILE, os.path.join(COOLQ_APP_DIR, CPK_NAME))
cqhttp_1   |   File "/usr/lib/python3.6/shutil.py", line 121, in copyfile
cqhttp_1   |     with open(dst, 'wb') as fdst:
cqhttp_1   | PermissionError: [Errno 13] Permission denied: '/home/user/coolq/app/io.github.richardchien.coolqhttpapi.cpk'
cqhttp_1   | ERROR: CQHTTP 插件 bootstrap 失败。
cqhttp_1   | [cont-init.d] 110-get-coolq: exited 0.
cqhttp_1   | [cont-init.d] 120-xstartup: executing... 
cqhttp_1   | [cont-init.d] 120-xstartup: exited 0.
cqhttp_1   | [cont-init.d] done.
cqhttp_1   | [services.d] starting services
cqhttp_1   | [services.d] done.
cqhttp_1   | xauth:  file /home/user/.Xauthority does not exist
cqhttp_1   | WebSocket server settings:
cqhttp_1   |   - Listen on :9001
cqhttp_1   |   - No SSL/TLS support (no cert file)
cqhttp_1   |   - proxying from :9001 to 127.0.0.1:5911
cqhttp_1   | 
cqhttp_1   | New 'd53dd8cd1b6c:11 (user)' desktop is d53dd8cd1b6c:11
cqhttp_1   | 
cqhttp_1   | Creating default config /home/user/.vnc/config
cqhttp_1   | Starting applications specified in /home/user/.vnc/xstartup
cqhttp_1   | Log file is /home/user/.vnc/d53dd8cd1b6c:11.log
cqhttp_1   | 
cqhttp_1   | [CQDaemon] Starting CoolQ ....
cqhttp_1   | [CQDaemon] Started CoolQ .

**Comment by jw-star** [comment]
这是dockerfile文件内容
FROM alpine
RUN apk add --no-cache tzdata python3 py3-multidict py3-yarl && \
        pip3 install --upgrade pip && \
        pip3 install --no-cache-dir "nonebot[scheduler]" && \
        pip3 install requests

**Comment by Ink-33** [comment]
```
cqhttp_1 | ERROR: [Errno 13] Permission denied: '/home/user/coolq/app/io.github.richardchien.coolqhttpapi.cpk'
```
```
cqhttp_1 | PermissionError: [Errno 13] Permission denied: '/home/user/coolq/app/io.github.richardchien.coolqhttpapi.cpk'
cqhttp_1 | ERROR: CQHTTP 插件 bootstrap 失败。
```
请检查一下目录`/home/user/coolq/app/`的权限配置，是否可读可写

**Comment by jw-star** [comment]
已解决，重试了两遍安装好了

**Comment by jw-star** [comment]
感谢！！
