### ISSUE TITLE
群组 At 也会被当做私聊处理

### ISSUE THREAD

**Issue by Konano** [nonebot/nonebot#172]
这是 Feature 还是 Bug……

**Comment by richardchien** [comment]
群组 at 会触发 command，这就是预期情况，如果需要停止响应群消息，可以参考 [这里](https://nonebot.cqp.moe/api.html#nonebot-permission-%E6%A8%A1%E5%9D%97)

**Comment by Konano** [comment]
可是为什么我设置了 PRIVATE_FRIEND 权限后还是能相应群组 at？这是预期的吗？

**Comment by richardchien** [comment]
看看完整代码？

**Comment by richardchien** [comment]
多半是因为你的 QQ 在 `SUPERUSERS` 里面

**Comment by Konano** [comment]
> 多半是因为你的 QQ 在 `SUPERUSERS` 里面

你说对了……SUPERUSERS 真就什么都触发……

**Comment by Konano** [comment]
请问有什么交流群之类的吗？有一些编程上的问题想要询问

**Comment by ExerciseBook** [comment]
telegram @cqhttp

**Comment by richardchien** [comment]
> 请问有什么交流群之类的吗？

README 里面有
