### ISSUE TITLE
[寻求帮助]怎么把pip3指向的版本从Python3.5.3（系统自带）改成Python3.8？

### ISSUE THREAD

**Issue by railannad** [nonebot/nonebot#173]
很抱歉来打扰，我知道这个问题本不该在这个项目下提问，但是我查了很久资料也没有解决，所以来这里寻求帮助，希望您可以回答我
操作环境是debian 9，系统自带python版本为3.5.3，按照nonebot官网的教程安装nonebot：

![image](https://user-images.githubusercontent.com/36919867/80294547-8426ba80-879c-11ea-967f-ead4b61ff8f2.png)
运行`python3.8 setup.py install` ，他提示缺少模块，但是用pip3安装模块他又提示模块已存在，输出的目录是python3.5，然而nonebot不支持python3.7以下的版本。

**Comment by yanyongyu** [comment]
试一试 `python3.8 -m pip -V` 确认是否是 python 3.8的pip

**Comment by momocow** [comment]
@yanyongyu 或者可以試試 pip3.8
