### ISSUE TITLE
[讨论] 关于持久化存储

### ISSUE THREAD

**Issue by winrey** [nonebot/nonebot#175]
有一些信息我认为是需要持久化存储的，而这是一个每个bot都会遇到的需求

比如某些群开关某插件的某功能，昵称等等的一些设置。

而需要持久化的数据，我觉得大体可以分为3个层次：

* 与个人绑定的数据（个人对bot的设置）
* 与群绑定的数据（群对bot的设置）
* 以及与 个人-群 关系 绑定数据。（某人在某群的昵称）
* <del>（其实也许还有和 个人-个人-群 关系 绑定的数据，单这真的是跑团bot才会有的小众需求了）</del>

建议用peewee等ORM模型，这样还可以做到后端可替换，默认可以用sqlite。
模型建成上述三种关系+key+value即可。

另外session其实也可以考虑持久化。

但是从另一个角度考虑，一个框架应该专注做好一件事，也许nonebot就不该考虑持久化的问题，而让用户自己选择？

--------------------

其实我个人实现这个需求用了monogo，完美契合，真香。。。。

**Comment by richardchien** [comment]
我之前就考虑过，如果要加持久化的话，应该直接用 mongodb，无脑塞就可以了，目前看来持久化这块可能还是用户自己选择比较好，更自由一些（我的奶茶机器人有些甚至是用文件存的 2333

**Comment by winrey** [comment]
有道理，那我close了～

**Comment by winrey** [comment]
> 我之前就考虑过，如果要加持久化的话，应该直接用 mongodb，无脑塞就可以了，目前看来持久化这块可能还是用户自己选择比较好，更自由一些（我的奶茶机器人有些甚至是用文件存的 2333

<del>用文件存的</del> 基于EXT/NFTS的文档对象存储系统
