### ISSUE TITLE
上一条命令被阻塞后，后续发送任何消息均被视为命令

### ISSUE THREAD

**Issue by chenxuan353** [nonebot/nonebot#186]
![image](https://user-images.githubusercontent.com/48858695/82537911-7129bf00-9b7d-11ea-94c2-a5a95d88210d.png)
不知道咋回事，被阻塞的情况类似#22的情况，已经尝试解决，还待后续观察。
目前连接了三个酷Q，国外服务器的两个，一个香港的，只有港服的出现了这样的问题。运营商是不同的三家搬瓦、vlutr、阿里云，其中香港的那一台是阿里云的centos7，运行nonebot的后端是vlutr ubuntu的系统。
另外nonebot的日志怎么记录到文件里呢。

**Comment by yanyongyu** [comment]
命令阻塞之后，后续的消息如果触发了命令（通过自然语言），将会提示用户当前正有命令运行（如同截图里的warning）

**Comment by chenxuan353** [comment]
自然语言没有和命令区分开，在有特殊情况被阻塞的时候就显得很奇怪

**Comment by yanyongyu** [comment]
看了一下，如果有命令在运行，再次发消息时确实都会触发 notify ，notify 内容可以自定义，最好还是直接解决阻塞部分或者使用 Apscheduler 让其在后台运行

**Comment by richardchien** [comment]
这个工作方式是符合预期的，因为自然语言最终也是触发一个特定命令，如果当前用户已经有命令在运行，那是进不去的，否则 session 就冲突了，耗时任务建议使用 `asyncio.create_task` 创建后台任务完成
