### ISSUE TITLE
如何使用临时会话让机器人发消息

### ISSUE THREAD

**Issue by WC12366** [nonebot/nonebot#187]
dalao请问一下，如果机器人和别人在同一个群里，如何通过临时会话在没有好友的情况下给那个人发送消息

**Comment by yanyongyu** [comment]
由于酷q的限制，只有在对方先给你发送过消息后（酷q存在关系记录）才能给那个人发送消息，使用接口 `send_private_msg` 即可

**Comment by WC12366** [comment]
那么这个关系记录是可以永久保存的吗

**Comment by richardchien** [comment]
> 那么这个关系记录是可以永久保存的吗

这个你需要去酷Q那边问问了
