### ISSUE TITLE
【提问】如何实现添加任务和计时器

### ISSUE THREAD

**Issue by Cyame** [nonebot/nonebot#188]
RT，想请教一下有没有性能更好的实现方式，大致涉及两个具体功能：

第一个是，想做一个留言板。因为一些大群会有消息很多，往回翻翻不到的情况，所以想做一个由管理员留言并记录，等到被留言者发消息时当面@并发送留言内容。
如果去做持续监听一直不处理线程的话 可行吗...总感觉会非常影响性能
同样的原理，想做一个复读机功能，大致逻辑想要：群员复读了10次之后，去跟着复读1次。这似乎不可避免地需要监听每条消息，然后放进队列，队列10个全部重复则排空并复读...如果这个功能和上述留言板一起实现...？感觉会很占资源所以想请教一下有没有更好的实现方式。

第二个是关于计时器，有点类似于第一个功能，但是是时间触发而非发言触发。就是想做一个DDL日志模块，由管理员布置DDL并规定时间，在期限中完成可以由管理员/当事人取消；否则在定时当日某时会报警提醒。这个功能或许要用自带的scheduler模块中的方法，想请问一下如果会话结束了，那么传给Scheduler的任务还会继续定时吗，又该如何监听呢（因为文档中只涉及了定时任务 有点摸不到头脑该如何实现）如果能新建内部任务的话或许可以这两个问题。

还请赐教Orz

**Comment by yanyongyu** [comment]
简单的看了下我觉得留言板用aspscheduler很容易实现，将留言的内容作为job，并给job一个特殊的id（包含目标qq），然后使用natural language监听消息，通过调用apscheduler的查询job的函数判断是否需要发送留言内容。这功能挺不错的。

**Comment by yanyongyu** [comment]
一旦apscheduler新建了任务就脱离了nonebot的命令响应，即便命令结束这个job还是在的。

**Comment by Yprolic** [comment]
正好给自己做了个闹钟，我的解决方案是从session拿了group_id和user_id，起个协程去处理，到时候直接用get bot发
`asyncio.ensure_future(timer(minute, session.event['user_id'], session.event.group_id))

async def timer(minute, user_id, group_id=None):
    await asyncio.sleep(minute * 60)
    bot = get_bot()
    if group_id:
        await bot.send_group_msg(group_id=group_id, message='[CQ:at,qq={0}]'.format(user_id))
    else:
        await bot.send_private_msg(user_id=user_id, message='时间到了')`

**Comment by richardchien** [comment]
> 第一个是，想做一个留言板。因为一些大群会有消息很多，往回翻翻不到的情况，所以想做一个由管理员留言并记录，等到被留言者发消息时当面@并发送留言内容。
> 如果去做持续监听一直不处理线程的话 可行吗...总感觉会非常影响性能
> 同样的原理，想做一个复读机功能，大致逻辑想要：群员复读了10次之后，去跟着复读1次。这似乎不可避免地需要监听每条消息，然后放进队列，队列10个全部重复则排空并复读...如果这个功能和上述留言板一起实现...？感觉会很占资源所以想请教一下有没有更好的实现方式。

留言功能看起来不需要定时器之类的东西，直接把留言内容存数据库就行，如果担心之后每条消息都要查数据库，那就把被留言者的 QQ 号放在内存，方便快速查询。

这个 issue 应该讨论清楚了，如果后续有问题再 reopen。
