### ISSUE TITLE
反向 WebSocket 连接尚未建立，无法上报

### ISSUE THREAD

**Issue by railannad** [nonebot/nonebot#189]
使用环境：Ubuntu18.04 nonebot+[hoshino](https://github.com/Ice-Cirno/HoshinoBot) coolq是在docker部署的
Linux命令行输出：（最上面只有两行没截到，没必要用第二张图了，直接放文字）
python3.8 run.py
ujson module not found, using json
![image](https://user-images.githubusercontent.com/36919867/82894340-044f6400-9f85-11ea-9e20-f0c691cde678.png)

cq http api 插件日志：
![image](https://user-images.githubusercontent.com/36919867/82894184-c2beb900-9f84-11ea-9c4a-aaca377083f2.png)

问题描述：本来用的好好的，昨天下午用宝塔面板装了[OLINDEX](https://imwnk.cn/archives/bt-olaindex)之后就不能用了，然后今天上午看到issue里面有人问类似的问题（[#73](https://github.com/nonebot/nonebot/issues/73)），起初我以为是端口占用，今天重装机子之后又用宝塔面板装了[oneindex+aira2](http://blog.lwc.im/2018/12/02/oneindex/) ，然后用`netstat   -nultp`命令查看端口使用情况，似乎并没有程序在使用8080端口。
从结果上看，两次错误（重装了一次机子又发生了一次）都是在用宝塔面板装完环境之后发生的。

![QQ图片20200526190604](https://user-images.githubusercontent.com/36919867/82893702-fea54e80-9f83-11ea-8b4f-a5c266d793d7.png)

我的nonebot插件（hoshino）和cq http api 配置文件如下：
![image](https://user-images.githubusercontent.com/36919867/82893968-71162e80-9f84-11ea-98e8-3d450ac21d4d.png)

![image](https://user-images.githubusercontent.com/36919867/82893811-30b6b080-9f84-11ea-8b2e-864dae3a8aad.png)

**Comment by railannad** [comment]
端口8088是因为我以为第一次的问题出在端口占用，我把两份配置文件都改了

**Comment by railannad** [comment]
刚发现cq http api日志里端口仍然是8080，不知道为什么没有变。
我把插件config和http api的json文件端口又改回了8080，依然是和之前一样的情况。  之前在QQ里发消息可以在Linux里看到，现在不行了
![image](https://user-images.githubusercontent.com/36919867/82896444-89884800-9f88-11ea-86e2-143cabb05e8b.png)
![image](https://user-images.githubusercontent.com/36919867/82896510-a91f7080-9f88-11ea-9db3-720ab08e48e7.png)

![image](https://user-images.githubusercontent.com/36919867/82896391-770e0e80-9f88-11ea-94a7-0fbfdef03395.png)

**Comment by yanyongyu** [comment]
在修改cqhttp配置之后是不是没有重启酷q，所以cqhttp依然尝试连接8080端口

**Comment by railannad** [comment]
> 在修改cqhttp配置之后是不是没有重启酷q，所以cqhttp依然尝试连接8080端口

![image](https://user-images.githubusercontent.com/36919867/82902124-92314c00-9f91-11ea-958c-c20661ed45e1.png)
![image](https://user-images.githubusercontent.com/36919867/82902132-965d6980-9f91-11ea-8bbb-b0bc29c4ae02.png)
重启了，端口也改了，但是还是建立失败

**Comment by yanyongyu** [comment]
如果确认防火墙已开放端口的话，尝试修改nonebot监听地址为 `0.0.0.0` 是否能连接成功

**Comment by yanyongyu** [comment]
> > 如果确认防火墙已开放端口的话，尝试修改nonebot监听地址为 `0.0.0.0` 是否能连接成功
> 
> 需要把http api 里面json文件的"ws_reverse_url": "ws://172.17.0.1:8866/ws/" 地址也改成0.0.0.0吗？ 插件config.py的监听端口改成-1会报错 ,似乎不行
> 我的机子的德国的contabo，应该没有防火墙吧，毕竟之前可以正常使用，只是装了宝塔之后就不行了.

cqhttp不需要动，宝塔面板是自带防火墙的，在宝塔-安全里开放端口

**Comment by railannad** [comment]
> > > 如果确认防火墙已开放端口的话，尝试修改nonebot监听地址为 `0.0.0.0` 是否能连接成功
> > 
> > 
> > 需要把http api 里面json文件的"ws_reverse_url": "ws://172.17.0.1:8866/ws/" 地址也改成0.0.0.0吗？ 插件config.py的监听端口改成-1会报错 ,似乎不行
> > 我的机子的德国的contabo，应该没有防火墙吧，毕竟之前可以正常使用，只是装了宝塔之后就不行了.
> 
> cqhttp不需要动，宝塔面板是自带防火墙的，在宝塔-安全里开放端口，nonebot监听地址暂时可以不动，先开放端口

没想到宝塔自带防火墙，放行了之后就可以了，感谢大佬

**Comment by railannad** [comment]
> > > > 如果确认防火墙已开放端口的话，尝试修改nonebot监听地址为 `0.0.0.0` 是否能连接成功
> > > 
> > > 
> > > 需要把http api 里面json文件的"ws_reverse_url": "ws://172.17.0.1:8866/ws/" 地址也改成0.0.0.0吗？ 插件config.py的监听端口改成-1会报错 ,似乎不行
> > > 我的机子的德国的contabo，应该没有防火墙吧，毕竟之前可以正常使用，只是装了宝塔之后就不行了.
> > 
> > 
> > cqhttp不需要动，宝塔面板是自带防火墙的，在宝塔-安全里开放端口，nonebot监听地址暂时可以不动，先开放端口
> 
> 没想到宝塔自带防火墙，放行了之后就可以了，感谢大佬
