### ISSUE TITLE
请问机器人怎么收到艾特

### ISSUE THREAD

**Issue by ayff** [nonebot/nonebot#196]
不知道怎么收到群里的艾特   在控制台看收到的是CQ：at，qq：。。。
但是直接把这个复制到命令名里面检测不到

我想实现在qq群里有人艾特机器人  后面不加任何别的文字 机器人就会出来回复
请问现在可以实现吗  如何实现  谢谢各位大佬

**Comment by richardchien** [comment]
参考 [这里](https://github.com/cczu-osa/aki/blob/master/aki/plugins/greeting.py#L14)

**Comment by ayff** [comment]
非常感谢  解决了~
