### ISSUE TITLE
使用Docker部署时出现的问题

### ISSUE THREAD

**Issue by haowen-li** [nonebot/nonebot#200]
建立容器时提示如下错误:

Starting ubuntu_dicepp_1 ...
Starting ubuntu_dicepp_1 ... done
Starting ubuntu_coolq_1 ...
Starting ubuntu_coolq_1 ... done
Attaching to ubuntu_dicepp_1, ubuntu_coolq_1
dicepp_1  | Traceback (most recent call last):
dicepp_1  |   File "/home/ubuntu/DicePP/dicepp.py", line 3, in <module>
dicepp_1  |     import nonebot
dicepp_1  |   File "/usr/lib/python3.6/site-packages/nonebot/__init__.py", line 5, in <module>
dicepp_1  |     import aiocqhttp.message
dicepp_1  |   File "/usr/lib/python3.6/site-packages/aiocqhttp/__init__.py", line 9, in <module>
dicepp_1  |     from .api import HttpApi, WebSocketReverseApi, UnifiedApi, ResultStore
dicepp_1  |   File "/usr/lib/python3.6/site-packages/aiocqhttp/api.py", line 8, in <module>
dicepp_1  |     import aiohttp
dicepp_1  |   File "/usr/lib/python3.6/site-packages/aiohttp/__init__.py", line 6, in <module>
dicepp_1  |     from .client import BaseConnector as BaseConnector
dicepp_1  |   File "/usr/lib/python3.6/site-packages/aiohttp/client.py", line 63, in <module>
dicepp_1  |     from .client_reqrep import ClientRequest as ClientRequest
dicepp_1  |   File "/usr/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 29, in <module>
dicepp_1  |     from . import hdrs, helpers, http, multipart, payload
dicepp_1  |   File "/usr/lib/python3.6/site-packages/aiohttp/multipart.py", line 703, in <module>
dicepp_1  |     class MultipartWriter(Payload):
dicepp_1  |   File "/usr/lib/python3.6/site-packages/aiohttp/multipart.py", line 786, in MultipartWriter
dicepp_1  |     headers: Optional[MultiMapping[str]]=None
dicepp_1  | TypeError: 'ABCMeta' object is not subscriptable
ubuntu_dicepp_1 exited with code 1

dockerfile如下:
`FROM alpine:3.7
COPY . /home/ubuntu/DicePP
RUN apk add --no-cache tzdata python3-dev py3-multidict py3-yarl && \
	apk add --no-cache gcc g++ make automake freetype-dev && \
	pip3 install --upgrade pip && \
    pip3 install --no-cache-dir "nonebot[scheduler]" && \
    pip3 install --no-cache-dir -r /home/ubuntu/DicePP/requirements.txt

CMD ["python3", "/home/ubuntu/DicePP/dicepp.py"]`

requirements里就是numpy和nonebot
谢谢!

**Comment by haowen-li** [comment]
还有一个问题就是build了以后即使删掉全部container和image依然还有好几gb的文件残留, 不知道是什么文件, 怎么删除呢?

**Comment by PhotonQuantum** [comment]
这应该是 multidict 版本过低造成的
建议 docker 直接 FROM python:alpine，并且 python 的依赖交给 pip 自己管理，不要用 alpine 包管理的 multidict 库，它可能太老了。
对于悬挂 image 的问题，可以尝试用 docker image prune 清理一下看看如何？

**Comment by haowen-li** [comment]
> 这应该是 multidict 版本过低造成的
> 建议 docker 直接 FROM python:alpine，并且 python 的依赖交给 pip 自己管理，不要用 alpine 包管理的 multidict 库，它可能太老了。
> 对于悬挂 image 的问题，可以尝试用 docker image prune 清理一下看看如何？

谢谢, 用python:alpine确实解决了问题, 但是占据的空间必须要用docker system prune -a 才能完全清理
