### ISSUE TITLE
能否在NLPsession中也加入挂起功能呢

### ISSUE THREAD

**Issue by Jim-Luo** [nonebot/nonebot#207]
NLPSession应该也像CommandSession一样有挂起功能，例如prompt，pause。因为在实际当中用户通过呼喊机器人名字和机器人对话，然后在同一次会话（session）中再和它对话不应该再呼喊名字，这样显得比较自然。

**Comment by richardchien** [comment]
按本来的设计，nlpsession 只是提供一个入口作用，把最初的一句话翻译成一个 command，之后的交互对话应该由 command 提供

**Comment by yanyongyu** [comment]
> 在同一次会话（session）中再和它对话不应该再呼喊名字，这样显得比较自然。

本来在有session等待的时候（session未超时、没有running中且存在）再次对话可以不需要呼喊名字
