### ISSUE TITLE
如何对写好的程序进行打包

### ISSUE THREAD

**Issue by xiaofentai** [nonebot/nonebot#208]
使用pyinstaller对写好的程序打包后，运行exe文件会出现无法加载awesome.pluins下的插件的报错，请问如何正确的对程序进行打包（项目有包含多个txt和图片文件，插件调用时都是用的相对路径）？

**Comment by yanyongyu** [comment]
> 使用pyinstaller对写好的程序打包后，运行exe文件会出现无法加载awesome.pluins下的插件的报错，请问如何正确的对程序进行打包（项目有包含多个txt和图片文件，插件调用时都是用的相对路径）？

在pyinstaller打包时得到spec文件里添加hidden import配置，详见pyinstaller文档。不是很建议打包成exe（
