### ISSUE TITLE
想问一下如何实现隔几秒钟发一条消息而不影响其他指令

### ISSUE THREAD

**Issue by chenshenwei1998** [nonebot/nonebot#211]
举个例子，我打算在某个command中连续发送两条消息，消息间隔5秒，我一开始尝试这么写
`session.send('balabala')`
`await asyncio.sleep(5)`
`session.send('balabala')`
结果确实是可以等待五秒发出下一条指令，但是如果在这五秒期间触发其他指令，就会出现“您有命令正在执行，请稍后再试”的提示，请问一下如何解决呢？非常感谢！

**Comment by lengthmin** [comment]
可以使用 apscheduler 将某一个任务放到后台来执行。
需要注意的是，不可以直接将 session 作为要执行任务的参数。可以参考一下其他的 issue #188 #162 

再看一下 apscheduler 的文档

简单写了个 demo：
```py
async def task(event):
    await _bot.send(event, 'balabala')
    await asyncio.sleep(5)
    await _bot.send(event, 'balabala')

@on_command("xx")
async def _(session):
    scheduler.add_job(task, args=[session.event])
```

**Comment by chenshenwei1998** [comment]
> 可以使用 apscheduler 将某一个任务放到后台来执行。
> 需要注意的是，不可以直接将 session 作为要执行任务的参数。可以参考一下其他的 issue #188 #162
> 
> 再看一下 apscheduler 的文档
> 
> 简单写了个 demo：
> 
> ```python
> async def task(event):
>     await _bot.send(event, 'balabala')
>     await asyncio.sleep(5)
>     await _bot.send(event, 'balabala')
> 
> @on_command("xx")
> async def _(session):
>     scheduler.add_job(task, args=[session.event])
> ```

懂了，非常感谢！
