### ISSUE TITLE
新人刚接触，群聊发消息无效，DEBUG: Not to me, ignored，求助

### ISSUE THREAD

**Issue by yaorelax** [nonebot/nonebot#212]

**Comment by lengthmin** [comment]
https://nonebot.cqp.moe/api.html#decorator-on-command-name-aliases-permission-perm-everybody-only-to-me-true-privileged-false-shell-like-false

![image](https://user-images.githubusercontent.com/13938334/89058673-4b494380-d392-11ea-9815-023581730463.png)
