### ISSUE TITLE
Cool Q好像不能用了

### ISSUE THREAD

**Issue by WC12366** [nonebot/nonebot#216]
今天发现CoolQ官网上面说明年二月份将关闭所有服务，今天已经无法登陆了

**Comment by Phoenixree** [comment]
你火星了，前段时间晨风作者被抓，昨天包括酷q在内的所有bot都停运了……

**Comment by cleoold** [comment]
https://www.zhihu.com/question/411466505

现在 mirai 比較熱鬧，如果用不了酷 Q 可以參考下 [cqhttp-mirai](https://github.com/yyuueexxiinngg/cqhttp-mirai) 和 [go-cqhttp](https://github.com/Mrs4s/go-cqhttp)

**Comment by mnixry** [comment]
Duplicate of #217
