### ISSUE TITLE
API 文档优化

### ISSUE THREAD

**Issue by richardchien** [nonebot/nonebot#221]
- [ ] `api.md` 文件拆分
- [ ] 文档自动生成

**Comment by cleoold** [comment]
怎样个自動生成？

**Comment by richardchien** [comment]
@cleoold 大概就是在代码里加上注释，然后就可以用工具生成了？

**Comment by mnixry** [comment]
> 怎样个自動生成？

使用Python的docstring生成，这样程序内的注释能够被快速同步到文档的API Reference，保证文档最新

**Comment by yanyongyu** [comment]
目前dev2分支使用sphinx(plugin: apidoc)配合sphinx-markdown-builder，自动转换docstring为markdown。

需要修改：
- sphinx rst模板
- sphinx-markdown-build样式，已fork：[nonebot/sphinx-markdown-builder](github.com/nonebot/sphinx-markdown-builder)

**Comment by yryd** [comment]
![image](https://user-images.githubusercontent.com/37370383/130552461-5aba745d-5e95-4f71-a913-78ec43da10ea.png)
这里面函数后面少打了冒号，望补充一下，谢谢

**Comment by mnixry** [comment]
> 这里面函数后面少打了冒号，望补充一下，谢谢

#274

**Comment by iyume** [comment]
#287
