### ISSUE TITLE
萌新不知道是哪里出了偏差(命令执行完对后续消息无响应)

### ISSUE THREAD

**Issue by bephbin51695** [nonebot/nonebot#229]
使用环境：centos7 python3.7 go-cqhttp-v0.9.17 nonebot-v1.6.0

go-cqhttp能正常收发消息
![image](https://user-images.githubusercontent.com/28349503/89894335-8823fe80-dc0c-11ea-8e01-089ea4ce491e.png)

nonebot在执行完第二条命令后，似乎卡住对后续消息无任何响应(敲回车也没用
![image](https://user-images.githubusercontent.com/28349503/89896511-29608400-dc10-11ea-9502-2301f6142d14.png)

qq的消息记录
![image](https://user-images.githubusercontent.com/28349503/89894809-50698680-dc0d-11ea-9e16-a02b9fe8dc49.png)

py代码
wn8.py
```
from nonebot import on_command, CommandSession
from lxml import etree
import requests

@on_command('wn8',only_to_me=False)

async def wn8(session: CommandSession):
    stripped_arg = session.current_arg_text.strip()
    name = stripped_arg
    if not stripped_arg:
        session.finish('请重试')
    wn8_report = await get_wn8_of_name(name)
    await session.send(wn8_report)

async def get_wn8_of_name(name: str) -> str:
    url = "https://wotlabs.net/sea/player/%s" %name
    response = requests.get(url)
    wb_data = response.text
    html = etree.HTML(wb_data)
    result = html.xpath('//*[@id="tankerStats"]/table/tbody/tr[14]/td[2]/text()')
    return f'{name}的wn8是%s' %result[0]
```

bot.py
```
from os import path
import nonebot
import config

if __name__ == '__main__':
    nonebot.init(config)
    nonebot.load_plugins(
        path.join(path.dirname(__file__), 'wot', 'plugins'),
        'wot.plugins'
    )
    nonebot.run()
```

**Comment by lengthmin** [comment]
看起来是 nonebot 并没有收到第三句消息，再多发几次 nonebot 依然收不到吗?

**Comment by bephbin51695** [comment]
@lengthmin go-cqhttp能收到，nonebot还是收不到

**Comment by yanyongyu** [comment]
@bephbin51695 询问了go-cqhttp作者，这个是他那边的bug，已经在[master](https://github.com/Mrs4s/go-cqhttp/tree/master)中修复
