### ISSUE TITLE
空命令

### ISSUE THREAD

**Issue by cleoold** [nonebot/nonebot#231]
**功能描述**
也就是當一條信息有且僅有機器人的暱稱時候，應該代表一個沒有名字，或者命令名為空無參數的命令。

```
> 小愛同學
我在！
> 明天天氣怎麼樣？
（調用天氣命令）
```

不知道為什麼空命令不被允許。

**理由**
見以上應用場景

**Comment by richardchien** [comment]
`on_natural_language` 的 `allow_empty_message` 参数可以做到接收无参数的「小爱同学」呼唤，再写一个命令去接收后续的输入，然后 `switch` 应该就行了
