### ISSUE TITLE
call command session终止，无法交互

### ISSUE THREAD

**Issue by Pzzzzz5142** [nonebot/nonebot#237]
**问题描述**
call command 创建的命令无法进入两次args parser

**复现方法**
<img width="140" alt="image" src="https://user-images.githubusercontent.com/31173671/93040223-0c3e2b80-f67c-11ea-991c-0731ca05438f.png">
<img width="154" alt="image" src="https://user-images.githubusercontent.com/31173671/93040689-22002080-f67d-11ea-8b62-30d169c5275a.png">

<img width="622" alt="image" src="https://user-images.githubusercontent.com/31173671/93040241-1829ed80-f67c-11ea-97c8-66ba44546242.png">

**期望的行为**
在call command新起一个command之后应该能完成`session.get()`函数。

**日志信息**
请附上 NoneBot 和 OneBot（CQHTTP）实现的运行日志（可截图或直接贴文本）。
<img width="852" alt="image" src="https://user-images.githubusercontent.com/31173671/93040315-532c2100-f67c-11ea-9868-b738b4542256.png">

**相关代码**
```python
from nonebot import on_command, CommandSession
from nonebot.command import call_command


@on_command("debug", only_to_me=False)
async def debug(session: CommandSession):
    x = session.get("x", prompt="这是x")
    x = session.get("y", prompt="这是y")
    x = session.get("z", prompt="这是z")

    if x == "ok":
        await call_command(session.bot, session.event, "debug")


@debug.args_parser
async def _(session: CommandSession):
    await session.send("IN ARGS PARSER")
    session.state[session.current_key] = session.current_arg_text.strip()

```

**运行环境**
 - 操作系统：Linux
 - OneBot（CQHTTP）实现及版本：go-cqhttp v0.9.24-fix2
 - NoneBot 版本：1.7.0
 - aiocqhttp 版本：1.3.0
 - Python 版本：3.7.6

**Comment by yanyongyu** [comment]
你的意思是 call command 调用的命令无法继续执行吗？如果是这样的话尝试这样

```diff
from nonebot import on_command, CommandSession
from nonebot.command import call_command


@on_command("debug", only_to_me=False)
async def debug(session: CommandSession):
    x = session.get("x", prompt="这是x")
    x = session.get("y", prompt="这是y")
    x = session.get("z", prompt="这是z")

    if x == "ok":
        await call_command(session.bot, session.event, "debug")
    
+      session.pause()


@debug.args_parser
async def _(session: CommandSession):
    await session.send("IN ARGS PARSER")
    session.state[session.current_key] = session.current_arg_text.strip()
```

**Comment by Pzzzzz5142** [comment]
> 你的意思是 call command 调用的命令无法继续执行吗？如果是这样的话尝试这样
> 
> ```diff
> @on_command("debug", only_to_me=False)
> async def debug(session: CommandSession):
>     x = session.get("x", prompt="这是x")
>     x = session.get("y", prompt="这是y")
>     x = session.get("z", prompt="这是z")
> 
>     if x == "ok":
>         futher_more = await call_command(session.bot, session.event, "debug")
>     
> +      if futher_more:
> +          session.pause()
> ```
> 
> 由于一个人在同一个群(私聊)同时只能拥有一个session，call command会覆盖session并在call_command首次运行结束后删除session所以无法二次响应。
> 
> 解决办法：
> 
> 添加session.pause()以维持session

很神奇的work了。说实话我还是不是很懂为什么call command是这样运行的。感觉`session.pause()`应当被整合进call command函数中，或者在文档中特别标注需要使用pause来维持session。（还是很想吐槽为什么call command需要further interaction的时候需要外层的命令来pause（（（

按理说如果是内联的（我也不知道该怎么准确称呼这种方式）调用命令的话，也不应该在call command后面pause，因为在需要further interaction的时候，那个命令并没有完成；如果是异步call的话，一个人又只能拥有一个session，就感觉两个命令同时发生，就很怪。（（（（

话说在这里通过`session.switch()`来转移命令感觉就（看起来）优雅一点（（（

**Comment by Pzzzzz5142** [comment]
这里我又做了一个测试。

```python
from nonebot import on_command, CommandSession
from nonebot.command import call_command


@on_command("debug", only_to_me=False)
async def debug(session: CommandSession):
    x = session.get("x", prompt="这是x")
    x = session.get("y", prompt="这是y")
    x = session.get("z", prompt="这是z")

    if x == "ok":
        await call_command(session.bot, session.event, "debug1")
        await call_command(session.bot, session.event, "debug2")
        await session.send("命令完成")
        await session.pause("123")
    await session.send("finished")


@debug.args_parser
async def _(session: CommandSession):
    await session.send("IN ARGS PARSER")
    session.state[session.current_key] = session.current_arg_text.strip()


@on_command("debug1", only_to_me=False)
async def debug1(session: CommandSession):
    x = session.get("x", prompt="这是x")
    x = session.get("y", prompt="这是y")
    x = session.get("z", prompt="这是z")


@debug1.args_parser
async def _(session: CommandSession):
    await session.send("IN ARGS PARSER 1")
    session.state[session.current_key] = session.current_arg_text.strip()


@on_command("debug2", only_to_me=False)
async def debug2(session: CommandSession):
    x = session.get("x", prompt="这是x")
    x = session.get("y", prompt="这是y")
    x = session.get("z", prompt="这是z")


@debug2.args_parser
async def _(session: CommandSession):
    await session.send("IN ARGS PARSER 2")
    session.state[session.current_key] = session.current_arg_text.strip()
```

只看最终的运行结果：
<img width="1488" alt="image" src="https://user-images.githubusercontent.com/31173671/93047491-34835580-f68f-11ea-8c8c-c2eafbf6e3b2.png">

在debug1和debug2都需要further interaction的时候，异步的跑完了debug1和debug2的args parser，然后debug2被`session.pause()`抛出的异常续命了，debug1就凌乱在风中了。如果call command本身不能完成多交互的命令还可以理解，但是文档中认为它支持啊（不然`disable_interaction=False`这个参数是用来干嘛的，，，）。。。就感觉，，，很怪。。。（（（

**Comment by yanyongyu** [comment]
在call_command里面pause是没有作用的，因为del session是发生在call_command外层命令结束时，他并不知道你内层调用了call_command并覆盖了自己的session

**Comment by yanyongyu** [comment]
> 在debug1和debug2都需要further interaction的时候，异步的跑完了debug1和debug2的args parser，然后debug2被`session.pause()`抛出的异常续命了，debug1就凌乱在风中了。如果call command本身不能完成多交互的命令还可以理解，但是文档中认为它支持啊（不然`disable_interaction=False`这个参数是用来干嘛的，，，）。。。就感觉，，，很怪。。。（（（

如果你需要同时call两个交互命令本身就有问题，用户到底和哪个交互呢

**Comment by Pzzzzz5142** [comment]
我对call command的理解是内联调用。也就是第一次是在与第一个命令交互，第二次是在与第二个命令交互。

**Comment by yanyongyu** [comment]
disable_interaction是强制不交互，即便他pause了也会被终止

**Comment by Pzzzzz5142** [comment]
（（（貌似理解上出了一点偏差

**Comment by Pzzzzz5142** [comment]
但是这又引出了另一个问题，就是在call需要交互的命令的时候，用户到底是在与outer command交互还是inner command交互？

因为我们可以明确的看到，在于inner command交互的时候需要outer command允许（也就是需要进行`session.puase()`操作。

**Comment by Pzzzzz5142** [comment]
ps：感觉说成阻塞调用更专业一点（（（（

**Comment by Pzzzzz5142** [comment]
> > 在debug1和debug2都需要further interaction的时候，异步的跑完了debug1和debug2的args parser，然后debug2被`session.pause()`抛出的异常续命了，debug1就凌乱在风中了。如果call command本身不能完成多交互的命令还可以理解，但是文档中认为它支持啊（不然`disable_interaction=False`这个参数是用来干嘛的，，，）。。。就感觉，，，很怪。。。（（（
> 
> 如果你需要同时call两个交互命令本身就有问题，用户到底和哪个交互呢

而且上述例子也不是同时调用的debug1和debug2啊，是在第一个call command结束后才调用的debug2。（（（

**Comment by yanyongyu** [comment]
> 但是这又引出了另一个问题，就是在call需要交互的命令的时候，用户到底是在与outer command交互还是inner command交互？
> 
> 因为我们可以明确的看到，在与inner command交互的时候需要outer command允许（也就是需要进行`session.pause()`操作。

call_command是直接覆盖当前session，也就是说，后续的所有交互都是在与inner交互，此时已经不存在outer了。只有第一次call_command的时候是存在outer的，因为outer command还没运行到return

**Comment by yanyongyu** [comment]
> 我对call command的理解是内联调用。也就是第一次是在与第一个命令交互，第二次是在与第二个命令交互。

这个你可以通过自行依次调用对应command.run来运行😂

**Comment by Pzzzzz5142** [comment]
那依照我感性的认知（原谅我实在没有看懂nb的源代码），应该在call command处做一个像是`session.get()`的断点及断点恢复的。因为call command覆盖当前session之后居然在运行了第一次inner command的args parser后又跑去异步运行outer command的内容去了。

现象：
<img width="1520" alt="image" src="https://user-images.githubusercontent.com/31173671/93050305-3bad6200-f695-11ea-9ec0-b6b2e19cc414.png">

代码：
```python
from nonebot import on_command, CommandSession
from nonebot.command import call_command
import asyncio


@on_command("debug", only_to_me=False)
async def debug(session: CommandSession):
    x = session.get("x", prompt="这是x")
    x = session.get("y", prompt="这是y")
    x = session.get("z", prompt="这是z")

    if x == "ok":
        await call_command(session.bot, session.event, "debug1")
        await session.send("蛤蛤蛤蛤")
        await session.pause("123")
    await session.send("finished")


@debug.args_parser
async def _(session: CommandSession):
    await session.send("IN ARGS PARSER")
    session.state[session.current_key] = session.current_arg_text.strip()


@on_command("debug1", only_to_me=False)
async def debug1(session: CommandSession):
    x = session.get("x", prompt="这是x")
    x = session.get("y", prompt="这是y")
    x = session.get("z", prompt="这是z")


@debug1.args_parser
async def _(session: CommandSession):
    await session.send("IN ARGS PARSER 1")
    session.state[session.current_key] = session.current_arg_text.strip()
```

如果有的话那就是阻塞调用了，也就能安安心心的与inner command交互而不用管outer command的脸色了/////。（大概也就不会有例二那种奇奇怪怪的问题了。毕竟你说这个是完全覆盖，但是这显然看起来它又去跑outer command后续的代码了，和inner command是同时异步运行的。

或者就直接补充一下文档，说call command本身是用于覆盖session，但是outer command本身的代码是和inner command同时运行的。（当作是一个feature，也就不用改代码了（（233

**Comment by yanyongyu** [comment]
@Pzzzzz5142 从代码上看，inner和outer不是同时运行的，call_command会等待inner运行结束后返回 asyncio.wait_for(future, timeout)
然后继续执行outer

**Comment by Pzzzzz5142** [comment]
但是从结果上看的确是同时运行的啊。
在进入debug1的args parser之后，在等待输入之前他输出了属于outer command的蛤蛤蛤蛤

**Comment by Pzzzzz5142** [comment]
![A597A3A3-D757-448B-9E1E-473B0644ED87](https://user-images.githubusercontent.com/31173671/93052900-8d57eb80-f699-11ea-917e-d78a0f3acfce.jpeg)

这个更明显一点

**Comment by yanyongyu** [comment]
@Pzzzzz5142 进入debug1 args_parser 然后发现没有x发送prompt，debug1就结束了，回到debug，发送后续的蛤和123

**Comment by Pzzzzz5142** [comment]
<img width="213" alt="image" src="https://user-images.githubusercontent.com/31173671/93054303-b2e5f480-f69b-11ea-876f-df23cee08ed6.png">

并不是这样的

代码：
```python 
from nonebot import on_command, CommandSession
from nonebot.command import call_command
import asyncio


@on_command("debug", only_to_me=False)
async def debug(session: CommandSession):
    x = session.get("x", prompt="这是x")
    x = session.get("y", prompt="这是y")
    x = session.get("z", prompt="这是z")

    if x == "ok":
        await call_command(session.bot, session.event, "debug1")
        await session.send("蛤蛤蛤蛤")
        await session.pause("123")
    await session.send("finished")


@debug.args_parser
async def _(session: CommandSession):
    await session.send("IN ARGS PARSER")
    session.state[session.current_key] = session.current_arg_text.strip()


@on_command("debug1", only_to_me=False)
async def debug1(session: CommandSession):
    x = session.get("x", prompt="这是x 1")
    x = session.get("y", prompt="这是y 1")
    x = session.get("z", prompt="这是z 1")


@debug1.args_parser
async def _(session: CommandSession):
    await session.send("IN ARGS PARSER 1")
    session.state[session.current_key] = session.current_arg_text.strip()
```

**Comment by Pzzzzz5142** [comment]
看了源代码，我大致明白call command是在干嘛了。。。。。（（（（（

也就是说call command只负责一次命令的运行。在命令本身抛出pause异常时（譬如`session.get()`和`session.pause()`），则会结束call command这个函数。而如果disable_interaction为False时，则会覆盖当前session，转而运行call command中的程序。同时由于call command已经结束了，所以会继续运行call command后的outer command的程序段，因为这一段已经在循环内，而且call command并没有抛出异常终止后续程序的运行。因此看起来像是outer command与inner command同时运行。

（建议在文档中说一下，因为现在看起来确实有点像是call command能够阻塞调用一个新的命令。实际上它只能阻塞调用一个命令的一次执行，同时会继续执行完outer command的剩余内容。而且当剩余部分outer command企图有交互时，也会被inner command拦截掉。

**Comment by cleoold** [comment]
> 
> 
> 看了源代码，我大致明白call command是在干嘛了。。。。。（（（（（
> 
> 也就是说call command只负责一次命令的运行。在命令本身抛出pause异常时（譬如`session.get()`和`session.pause()`），则会结束call command这个函数。而如果disable_interaction为False时，则会覆盖当前session，转而运行call command中的程序。同时由于call command已经结束了，所以会继续运行call command后的outer command的程序段，因为这一段已经在循环内，而且call command并没有抛出异常终止后续程序的运行。因此看起来像是outer command与inner command同时运行。
> 
> （建议在文档中说一下，因为现在看起来确实有点像是call command能够阻塞调用一个新的命令。实际上它只能阻塞调用一个命令的一次执行，同时会继续执行完outer command的剩余内容。而且当剩余部分outer command企图有交互时，也会被inner command拦截掉。

可以體驗一下 Master 分支的 [`apause/aget`](https://github.com/nonebot/nonebot/pull/232) 系列，或許可以解決你的需求。
