### ISSUE TITLE
如何通过http而不是ws的方式连接cqhttp

### ISSUE THREAD

**Issue by anaivebird** [nonebot/nonebot#254]
如何通过http而不是ws的方式连接cqhttp

**Comment by yanyongyu** [comment]
使用 `aiocqhttp` 或者 `nonebot2` （

**Comment by mnixry** [comment]
您指的是哪种连接方式

- 正向ws 
- 正向http
- 反向ws
- 反向http

**Comment by ExerciseBook** [comment]
@yanyongyu nonebot 是同时支持反向 http 和反向 ws 的。
我想起了我第一次用 nonebot，我在 onebot 设置里把 http 和 ws 都设置了，然后我的机器人把所有的消息都响应了两次。

**Comment by anaivebird** [comment]
都可以，我想知道的只是在哪里配置连接方式，找了很久文档没找到

**Comment by yanyongyu** [comment]
噗，太久没看忘记了，使用 http post 请求上报 nonebot `http://host:port/`，并配置 `API_ROOT` 用于调用api接口

**Comment by cleoold** [comment]
依照此設置即可：

config.py
```py
HOST = '127.0.0.1'
PORT = 8765
API_ROOT = 'http://127.0.0.1:8764'
ACCESS_TOKEN = 'accesstoken'
SECRET = 'secret'
```

bot.py
```py
nonebot.run(host=config.HOST, port=config.PORT)
```

gocqhttp:
```json
	"access_token": "accesstoken",
	"http_config": {
		"enabled": true,
		"host": "127.0.0.1",
		"port": 8764,
		"timeout": 0,
		"post_urls": { "127.0.0.1:8765": "secret" },
		"post_message_format": "string"
	},
```

黨沒有 WS 鏈接的時候就會自動選擇 HTTP 方式。

https://github.com/nonebot/nonebot/blob/fd7252fc699d7d80eb791c9386e285a5226e56d1/nonebot/__init__.py#L29
https://github.com/nonebot/aiocqhttp/blob/a48d65e1832cb69681ca1b5fcf88dea626cd0b6d/aiocqhttp/__init__.py#L128
