### ISSUE TITLE
请问如何在只是User is calling me的情况下保持会话？

### ISSUE THREAD

**Issue by jiaxinonly** [nonebot/nonebot#258]
请问有办法在只@机器人或者只输入了机器人昵称的情况下进行回复并保持会话吗？
如
我：小明
小明（机器人）：在呢？
我：成都天气
小明（机器人）：成都，晴。。。。
现在，如果只是输入小明，只是会User is calling me，命令为‘’，不会执行任何命令
![image](https://user-images.githubusercontent.com/57223696/103354250-057ddc00-4ae6-11eb-8369-9c5eb28d0196.png)

**Comment by cleoold** [comment]
https://github.com/nonebot/nonebot/issues/231

**Comment by cleoold** [comment]
如果問題解決了那麽就先關閉吧
