### ISSUE TITLE
scheduler与message_preprocessor不在同一个eventloop导致两者之间很难进行同步

### ISSUE THREAD

**Issue by qq1176321897** [nonebot/nonebot#259]
**问题描述**
scheduler与message_preprocessor不在同一个eventloop，如果使用asyncio.Lock()进行同步，会报错future attached to a different loop

**复现方法**
在scheduler与message_preprocessor中对同一个asyncio.Lock()进行acquire()

**日志信息**
![image](https://user-images.githubusercontent.com/34051396/104731525-c783e780-5776-11eb-9646-44514b1d03c6.png)

**相关代码**
https://github.com/Ice-Cirno/HoshinoBot
https://github.com/qq1176321897/pcrjjc2/commit/b9cc6cfe6441b253a2248d7b91d7ca5ec7b5f32f

**运行环境**
 - 操作系统：
 - OneBot（CQHTTP）实现及版本：onebot-kotlin-0.3.3-all
 - NoneBot 版本：1.6.0
 - aiocqhttp 版本：1.2.5
 - Python 版本：3.8.5

**Comment by mnixry** [comment]
试试用[信号量](https://docs.python.org/zh-cn/3/library/asyncio-sync.html#asyncio.Semaphore)代替Lock

**Comment by mnixry** [comment]
https://github.com/qq1176321897/pcrjjc2/blob/ad107267b3d58b318dd3c0f7fed485dce2fca234/query.py#L38-L44
看起来你在代码中你自行在一个新的线程中创建了一个新的事件循环

**Comment by qq1176321897** [comment]
> https://github.com/qq1176321897/pcrjjc2/blob/ad107267b3d58b318dd3c0f7fed485dce2fca234/query.py#L38-L44
> 看起来你在代码中你自行在一个新的线程中创建了一个新的事件循环

因为感觉没办法在一个loop获取另一个loop就只能新建了 只能拿自旋锁防止阻塞同时同步两个loop

**Comment by mnixry** [comment]
> > https://github.com/qq1176321897/pcrjjc2/blob/ad107267b3d58b318dd3c0f7fed485dce2fca234/query.py#L38-L44
> > 看起来你在代码中你自行在一个新的线程中创建了一个新的事件循环
> 
> 因为感觉没办法在一个loop获取另一个loop就只能新建了 只能拿自旋锁防止阻塞同时同步两个loop

插件加载的时候事件循环已经初始化了, 你可以使用`get_bot().loop`来获取这个事件循环
另外你还可以参考使用[`run_coroutine_threadsafe`](https://docs.python.org/zh-cn/3/library/asyncio-task.html?highlight=run_coroutine#asyncio.run_coroutine_threadsafe)函数
    - P.S 该函数是为数不多需要显式传递loop参数的函数, 其他大多数asyncio的函数的loop形参都已经被标记为弃用并将在之后的Python版本中被移除

**Comment by qq1176321897** [comment]
> > > https://github.com/qq1176321897/pcrjjc2/blob/ad107267b3d58b318dd3c0f7fed485dce2fca234/query.py#L38-L44
> > > 看起来你在代码中你自行在一个新的线程中创建了一个新的事件循环
> > 
> > 
> > 因为感觉没办法在一个loop获取另一个loop就只能新建了 只能拿自旋锁防止阻塞同时同步两个loop
> 
> 插件加载的时候事件循环已经初始化了, 你可以使用`get_bot().loop`来获取这个事件循环
> 
> * 另外你还可以参考使用[`run_coroutine_threadsafe`](https://docs.python.org/zh-cn/3/library/asyncio-task.html?highlight=run_coroutine#asyncio.run_coroutine_threadsafe)函数
>   
>   * P.S 该函数是为数不多需要显式传递loop参数的函数, 其他大多数asyncio的函数的loop形参都已经被标记为弃用并将在之后的Python版本中被移除

感谢帮助，虽然那个get_boot().loop最后是None，但是通过get_event_loop()的方式最终还是解决了

**Comment by mnixry** [comment]
https://github.com/agronholm/apscheduler/commit/0b02d77ef70bdc16a7f2ed65d9b6bbb5b15c17a9
看起来 apscheduler 确实是有这个问题, 不过已经在 apscheduler 3.7.0中被修复了

我会更新nonebot的依赖版本到apscheduler3.7来修复这个问题
