### ISSUE TITLE
nonebot+cqhttp反向websocket 时出现错误: websocket: bad handshake

### ISSUE THREAD

**Issue by borgeens** [nonebot/nonebot#262]
连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/cqhttp/ws 时出现错误: websocket: bad handshake

连接到反向WebSocket Universal服务器 ws://127.0.0.1:8080/cqhttp/ws 时出现错误: websocket: bad handshake

配置文件如下
{
uin: 117
password: "000"
encrypt_password: false
password_encrypted: ""
enable_db: true
access_token: ""
relogin: {
enabled: true
relogin_delay: 3
max_relogin_times: 0
}
_rate_limit: {
enabled: false
frequency: 1
bucket_size: 1
}
ignore_invalid_cqcode: false
force_fragmented: false
heartbeat_interval: 0
http_config: {
enabled: false
host: "0.0.0.0"
port: 5700
timeout: 0
post_urls: {}
}
ws_config: {
enabled: false
host: "0.0.0.0"
port: 6700
}
ws_reverse_servers: [
{
enabled: true
reverse_url: ws://127.0.0.1:8080/cqhttp/ws
reverse_api_url: ws://you_websocket_api.server
reverse_event_url: ws://you_websocket_event.server
reverse_reconnect_interval: 3000
}
]
post_message_format: array
use_sso_address: false
debug: false
log_level: ""
web_ui: {
enabled: false
host: 127.0.0.1
web_ui_port: 9999
web_input: false
}
}

使用了python
import nonebot

if name == 'main':
nonebot.init()
nonebot.load_builtin_plugins()
nonebot.run(host='127.0.0.1', port=8080)

求教求教

有python的demo也行呀。

**Comment by yanyongyu** [comment]
你使用的上报地址是nonebot2的但你写的代码是nonebot1的

**Comment by sam01101** [comment]
进群问问也不至于开issue问

**Comment by borgeens** [comment]
> 进群问问也不至于开issue问

没有找到群呀。我也不爱在这里问，很麻烦.

**Comment by borgeens** [comment]
> 你使用的上报地址是nonebot2的但你写的代码是nonebot1的，两个版本写法完全不同
> 
> 参考文档：
> 
> * [nonebot1](docs.nonebot.dev)
> * [nonebot2](v2.nonebot.dev)

求教，nonebot2+cqhttp可以吗？
还是需要Mirai +nonebot2？

**Comment by borgeens** [comment]
> 你使用的上报地址是nonebot2的但你写的代码是nonebot1的，两个版本写法完全不同
> 
> 参考文档：
> 
> * [nonebot1](docs.nonebot.dev)
> * [nonebot2](v2.nonebot.dev)

我提问的时候复制错了，实际上url是一样的。127.0.0.1：5540

**Comment by yanyongyu** [comment]
nonebot1请使用ws://127.0.0.1:8080/ws进行连接

**Comment by sam01101** [comment]
> > 进群问问也不至于开issue问
> 
> 没有找到群呀。我也不爱在这里问，很麻烦.

哈哈，真的没群呢。

![Screenshot_20210324-015806](https://user-images.githubusercontent.com/25792361/112194998-68de5c80-8c44-11eb-8ecc-7513bd02a34a.png)

**Comment by richardchien** [comment]
> 进群问问也不至于开issue问

用 issue 问挺好的，issue 就是干这个的

**Comment by sam01101** [comment]
> > 进群问问也不至于开issue问
> 
> 用 issue 问挺好的，issue 就是干这个的

issue是给你反馈程序的bug，如果每个人都这样问那么开发者会非常困扰的

你这些问题已经在文档了，自己又不去看
而且Discussion又不用，偏要在这里问

这就是为什么mirai限制开issue，vue直接不让你在github开issue的原因

就是因为你们这些无关重要的小问题，而导致开发者要额外多花时间去回答
明明走进群问下就有了帮你了，你偏爱在这里问
为什么呢？

> issue不是问问题的question issue，是回报程序错误的bug issue

**Comment by richardchien** [comment]
> > > 进群问问也不至于开issue问
> > 
> > 
> > 用 issue 问挺好的，issue 就是干这个的
> 
> issue是给你反馈程序的bug，如果每个人都这样问那么开发者会非常困扰的
> 
> 你这些问题已经在文档了，自己又不去看
> 而且Discussion又不用，偏要在这里问
> 
> 这就是为什么mirai限制开issue，vue直接不让你在github开issue的原因
> 
> 就是因为你们这些无关重要的小问题，而导致开发者要额外多花时间去回答
> 明明走进群问下就有了帮你了，你偏爱在这里问
> 为什么呢？
> 
> > issue不是问问题的question issue，是回报程序错误的bug issue

虽然已经 off topic 了，但是谢谢你教我做事。

作为 CQHTTP 和 NoneBot 的创造者和核心开发者，我一直是允许在 issue 里问关于项目使用的问题的，并且有一个叫做 `question` 的 issue label 专门用于归类“Questions on the usage of the program”。在我看来，询问使用上的问题是 issue 众多功能之一，相比 QQ 群它可以更好的保存前人遇到的问题和解决方案。

当然了，GitHub 前段时间确实出了个 discussion 功能，NoneBot 也在 https://github.com/nonebot/discussions/discussions 开了这个功能，但这玩意存在感低到我都忘了这事，用户不知道在这发问题是完全可以理解的。

至于你说的 mirai 和 vue 限制 issue 功能，不允许发提问，那是它们的开发者的个人选择，请不要把别人的选择强加到我的项目上来。

再看这个 issue 本身，提问者并非完全没有提供他的报错具体信息，而是给出了报错内容、URL、配置、代码，只是他不太会用 markdown 更好地整理和展示，同时态度非常谦逊，是抱着解决问题的心态来问的，完全无可非议。

有一些琐碎的小问题确实可以在 QQ 群解决，你可以提议让他加 QQ 群询问，但不至于像下面这样傲慢和阴阳怪气：

> 进群问问也不至于开issue问

> 哈哈，真的没群呢。

**Comment by sam01101** [comment]
首先，我想说明一下用意：
我怎么做的目的是因为不想让开发者被过多的提问所困扰，
作为一个开发者，我知道自身的经验肯定没你的多，但我也有所体会
当一个用户提出问题，当然可以，也乐意去解答
但如果当一个问题被重复提出过多次，便会对开发者造成困扰
而且并因为要解答问题而浪费了时间
这些时间你可以拿去改善bug，添加新的功能，写出更好的代码

举例，https://github.com/Mrs4s/go-cqhttp/issues/633 这里是我透过每个用户提出的问题而整理出来的文档
初衷就是因为太多的用户提出相近的问题和提问教程，为了不浪费大家的时间而写出来的

以这个issue为例，这个问题已经被提问过多次了，而且如果根据这里的[教程](https://v2.nonebot.dev/guide/loading-a-plugin.html) ( https://v2.nonebot.dev/guide/loading-a-plugin.html )，我相信这个issue就不会出现了。

至于上面yygq的发言，我这里已经非常克制自己并在努力改善了
我知道自己有这个问题，如果造成了困扰这里先道歉
如果是以前的了，估计就会一言不合就骂人了吧。

上面也不断提示可以到用户群提问，因为用户群里面可以得到即时的回复，节省等待开发者回答的时间
我并不觉得进去QQ群提问是一件困难的事情

我举例mirai和vue的例子并没有说过不允许用户提问，他们也是可以提问的，但在这之前会有一些预先说明去引导他们到其他地方看看有没有重复的问题
这样可以节省双方的时间，何乐而不为
至于开发者的选择，我并不认为一个开发者能够左右整个项目，但在你的回复里，你说了一个开发者就有权限决定整个项目
并，我并没有强加“别人的选择”到这个项目里，这是你个人的理解错误

Discussion确实是一个新功能，这个功能其实类似stackoverflow之类的提问解答网站，也像一个论坛
我认为开发者其实有引导用户使用这个功能的责任在。
当然，这是我的建议，希望你不要认为这是我强加“别人的选择“到这里

我对用户用issue提出问题确实是比较抗拒，但也只是不喜欢提出相同的问题的issue
如果这个问题本身是没有人提出过，我当然也欢迎。

其实回到根本，如果文档和说明充足，加上用户愿意花一些精力去看这些经过贡献者和开发者写的文字
我相信不会出现这么多的提问
因为大部分的问题其实都已经包含在文档的说明里面了。

**Comment by sam01101** [comment]
这个回复我已经花了比较多的时间去分析和写，希望你不要反驳我的观点
当然，如果有错你可以提出，我会去修改

![B1592A8C-104D-406C-B32A-006C98382D13](https://user-images.githubusercontent.com/25792361/112420307-f4044300-8d67-11eb-8b67-176bca32dc1e.png)

**Comment by cleoold** [comment]
```diff
ws_reverse_servers: [
{
  enabled: true
-  reverse_url: ws://127.0.0.1:8080/cqhttp/ws
+  reverse_url: ws://127.0.0.1:8080/ws
  reverse_api_url: ws://you_websocket_api.server
  reverse_event_url: ws://you_websocket_event.server
  reverse_reconnect_interval: 3000
}
```
是的，這樣應該就 OK 了。
