### ISSUE TITLE
[提问]如何关闭heartbeat的logging

### ISSUE THREAD

**Issue by yoooowi** [nonebot/nonebot#264]
logger似乎会在每次收到CQHTTP的heartbeat时log一次，请问有什么办法可以关掉吗？
![screenshot](https://user-images.githubusercontent.com/67884123/112812075-48345d80-90af-11eb-8ca0-d87fb421a124.JPG)

**Comment by cleoold** [comment]
這是 aiocqhttp 的 log，如果只是關閉心跳 log 的話好像沒有辦法。

如果不在意別種類的 log 也被關閉的話，可以試試：
```py
import logging

get_bot().logger.setLevel(logging.WARNING)
```

**Comment by cleoold** [comment]
請問問題解決了嗎？

如果太長時間沒有回覆我會關閉 issue

**Comment by yoooowi** [comment]
并没有 设成WARNING的话会漏掉一些有用的log 没想到什么好的办法

**Comment by cleoold** [comment]
那可以説是 aiocqhttp 的設計了。從設計來説心跳也是收到的消息，和其他的消息沒有區別，而 logging 就是盡可能地輸出足夠的消息來追溯。

試一下 filter 吧：
https://docs.python.org/3/library/logging.html#logging.Logger.addFilter

**Comment by cleoold** [comment]
咋人又没了捏 🤔

**Comment by yoooowi** [comment]
不好意思忘记回复了 filter似乎可以用 谢谢！
